name: Manual Windows 11 x64 Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Brave Browser for Windows 11 x64
    runs-on: self-hosted
    timeout-minutes: 360 # building Brave may take several hours

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Chocolatey dependencies (Visual Studio Build Tools, Ninja)
        run: |
          choco install -y visualstudio2022buildtools visualstudio2022-workload-vctools ninja

      - name: Set up depot_tools in PATH
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install npm dependencies
        run: npm install

      - name: Bootstrap Chromium and Brave-core (npm run init)
        run: npm run init

      - name: Build Brave in Release mode
        run: npm run build Release

      - name: Upload Brave Release binary
        uses: actions/upload-artifact@v4
        with:
          name: brave-windows-x64-release
          path: src/brave/out/Release/brave.exe
