name: Manual Windows 11 x64 Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Brave Browser for Windows 11 x64
    runs-on: windows-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Chocolatey dependencies (Visual Studio Build Tools, Ninja)
        run: |
          choco install -y visualstudio2022buildtools visualstudio2022-workload-vctools ninja

      - name: Set up depot_tools in PATH
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          echo "$PWD/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Fetch Brave source (official upstream)
        run: |
          mkdir brave-src
          cd brave-src
          fetch --nohooks brave
        shell: bash

      - name: Run hooks (gclient)
        run: |
          cd brave-src
          gclient runhooks
        shell: bash

      - name: Build Brave (Release, x64)
        run: |
          cd brave-src/src
          gn gen out/Release --args="is_official_build=true is_component_build=false brave_channel=\"stable\" target_cpu=\"x64\""
          ninja -C out/Release brave
        shell: bash

      - name: Upload Brave Release binary
        uses: actions/upload-artifact@v4
        with:
          name: brave-windows-x64-release
          path: brave-src/src/out/Release/brave.exe
