name: Build Brave Browser (Self-Hosted Windows)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'Release'
        type: choice
        options:
        - Release
        - Component
        - Debug
        - Static

jobs:
  build:
    name: Build Brave Browser for Windows x64
    runs-on: self-hosted
    timeout-minutes: 480 # 8 hours for initial build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: System Information
        shell: powershell
        run: |
          try {
            Write-Host "=== System Information ==="
            
            # Get OS Info
            $os = Get-WmiObject Win32_OperatingSystem
            Write-Host "OS: $($os.Caption) $($os.Version)"
            Write-Host "Architecture: $($os.OSArchitecture)"
            
            # Get Memory Info
            $memory = Get-WmiObject Win32_ComputerSystem
            $totalMemoryGB = [math]::Round($memory.TotalPhysicalMemory / 1GB, 2)
            Write-Host "Total Memory: $totalMemoryGB GB"
            
            # Get Disk Info
            Write-Host "=== Disk Space ==="
            Get-WmiObject Win32_LogicalDisk | Where-Object { $_.DriveType -eq 3 } | ForEach-Object {
              $freeGB = [math]::Round($_.FreeSpace / 1GB, 2)
              $sizeGB = [math]::Round($_.Size / 1GB, 2)
              Write-Host "Drive $($_.DeviceID) - Total: $sizeGB GB, Free: $freeGB GB"
            }
            
            # Get CPU Info
            $cpu = Get-WmiObject Win32_Processor | Select-Object -First 1
            Write-Host "CPU: $($cpu.Name)"
            Write-Host "Cores: $($cpu.NumberOfCores)"
            
          } catch {
            Write-Host "Error getting system info: $($_.Exception.Message)"
            Write-Host "Continuing anyway..."
          }

      - name: Check Prerequisites
        shell: powershell
        run: |
          Write-Host "=== Checking Prerequisites ==="
          
          # Check depot_tools
          try {
            $gclientPath = Get-Command gclient -ErrorAction Stop
            Write-Host "✅ depot_tools found at: $($gclientPath.Source)"
            gclient --version
          } catch {
            Write-Host "❌ depot_tools not found in PATH"
            Write-Host "Current PATH: $env:PATH"
            Write-Host "Please ensure depot_tools is installed and in PATH"
            exit 1
          }
          
          # Check Visual Studio Build Tools
          $vsWhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          if (Test-Path $vsWhere) {
            Write-Host "✅ Visual Studio Build Tools found"
            try {
              & $vsWhere -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64
            } catch {
              Write-Host "Warning: Could not query Visual Studio details"
            }
          } else {
            Write-Host "❌ Visual Studio Build Tools not found at $vsWhere"
            Write-Host "Please install Visual Studio 2022 Build Tools with C++ workload"
            exit 1
          }
          
          # Check Node.js and npm
          try {
            $nodeVersion = node --version
            $npmVersion = npm --version
            Write-Host "✅ Node.js version: $nodeVersion"
            Write-Host "✅ npm version: $npmVersion"
          } catch {
            Write-Host "❌ Node.js or npm not found"
            Write-Host "Please install Node.js 18.x or later"
            exit 1
          }

      - name: Set environment variables
        shell: powershell
        run: |
          Write-Host "Setting environment variables..."
          echo "DEPOT_TOOLS_WIN_TOOLCHAIN=0" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "GCLIENT_PY3=1" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "Environment variables set"

      - name: Install npm dependencies
        shell: powershell
        run: |
          Write-Host "Installing npm dependencies..."
          npm install

      - name: Initialize Brave (npm run init)
        shell: powershell
        run: |
          Write-Host "Starting Brave initialization..."
          Write-Host "This will download Chromium source (~30GB) - may take 30-60 minutes"
          npm run init
        env:
          DEPOT_TOOLS_WIN_TOOLCHAIN: 0
          GCLIENT_PY3: 1

      - name: Build Brave
        shell: powershell
        run: |
          Write-Host "Building Brave in ${{ github.event.inputs.build_type }} mode..."
          Write-Host "This may take 1-3 hours depending on your hardware"
          npm run build ${{ github.event.inputs.build_type }}
        env:
          DEPOT_TOOLS_WIN_TOOLCHAIN: 0

      - name: Verify build output
        shell: powershell
        run: |
          $buildType = "${{ github.event.inputs.build_type }}"
          $binaryPath = "src\out\$buildType\brave.exe"
          if (Test-Path $binaryPath) {
            Write-Host "✅ Build successful!"
            Write-Host "Binary location: $binaryPath"
            $fileInfo = Get-Item $binaryPath
            Write-Host "File size: $([math]::Round($fileInfo.Length/1MB, 2)) MB"
            Write-Host "Created: $($fileInfo.CreationTime)"
          } else {
            Write-Host "❌ Build failed - brave.exe not found at $binaryPath"
            Write-Host "Checking output directory contents:"
            if (Test-Path "src\out\$buildType") {
              Get-ChildItem "src\out\$buildType" | Select-Object Name, Length, LastWriteTime
            } else {
              Write-Host "Output directory src\out\$buildType does not exist"
            }
            exit 1
          }

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: brave-windows-x64-${{ github.event.inputs.build_type }}-${{ github.run_number }}
          path: |
            src/out/${{ github.event.inputs.build_type }}/brave.exe
            src/out/${{ github.event.inputs.build_type }}/*.dll
            src/out/${{ github.event.inputs.build_type }}/resources/
          retention-days: 30
        if: success()

      - name: Cleanup on failure
        if: failure()
        shell: powershell
        run: |
          Write-Host "Build failed. Checking disk space and recent logs..."
          try {
            Get-WmiObject Win32_LogicalDisk | Where-Object { $_.DriveType -eq 3 } | ForEach-Object {
              $freeGB = [math]::Round($_.FreeSpace / 1GB, 2)
              Write-Host "Drive $($_.DeviceID) Free: $freeGB GB"
            }
          } catch {
            Write-Host "Could not get disk space info"
          }
          
          # Check if there are any build logs to examine
          if (Test-Path "src\out") {
            Write-Host "Contents of src\out:"
            Get-ChildItem "src\out" -Recurse -Name | Select-Object -First 20
          }
